In [1]:
import pandas as pd

train = pd.read_csv("train.csv")
meal = pd.read_csv("meal_info.csv")
center = pd.read_csv("fulfilment_center_info.csv")

print("All files loaded successfully ✅")

All files loaded successfully ✅

In [2]:
data = pd.merge(train, meal, on="meal_id")

In [3]:
data = pd.merge(data, center, on="center_id")

In [4]:
data.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,category,cuisine,city_code,region_code,center_type,op_area
0,1379560,1,55,1885,136.83,152.29,0,0,177,Beverages,Thai,647,56,TYPE_C,2.0
1,1466964,1,55,1993,136.83,135.83,0,0,270,Beverages,Thai,647,56,TYPE_C,2.0
2,1346989,1,55,2539,134.86,135.86,0,0,189,Beverages,Thai,647,56,TYPE_C,2.0
3,1338232,1,55,2139,339.50,437.53,0,0,54,Beverages,Indian,647,56,TYPE_C,2.0
4,1448490,1,55,2631,243.50,242.50,0,0,40,Beverages,Indian,647,56,TYPE_C,2.0

In [5]:
data = data.drop(["emailer_for_promotion", "homepage_featured"], axis=1)

In [6]:
data.head()

,id,week,center_id,meal_id,checkout_price,base_price,num_orders,category,cuisine,city_code,region_code,center_type,op_area
0,1379560,1,55,1885,136.83,152.29,177,Beverages,Thai,647,56,TYPE_C,2.0
1,1466964,1,55,1993,136.83,135.83,270,Beverages,Thai,647,56,TYPE_C,2.0
2,1346989,1,55,2539,134.86,135.86,189,Beverages,Thai,647,56,TYPE_C,2.0
3,1338232,1,55,2139,339.50,437.53,54,Beverages,Indian,647,56,TYPE_C,2.0
4,1448490,1,55,2631,243.50,242.50,40,Beverages,Indian,647,56,TYPE_C,2.0

In [7]:
data_sorted = data.sort_values(by="num_orders", ascending=False)

In [8]:
data_top10k = data_sorted.head(10000)

In [9]:
data_top10k.shape

(10000, 13)

In [10]:
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456548 entries, 0 to 456547
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              456548 non-null  int64
 1   week            456548 non-null  int64
 2   center_id       456548 non-null  int64
 3   meal_id         456548 non-null  int64
 4   checkout_price  456548 non-null  float64
 5   base_price      456548 non-null  float64
 6   num_orders      456548 non-null  int64
 7   category        456548 non-null  object
 8   cuisine         456548 non-null  object
 9   city_code       456548 non-null  int64
 10  region_code     456548 non-null  int64
 11  center_type     456548 non-null  object
 12  op_area         456548 non-null  float64
dtypes: float64(3), int64(7), object(3)
memory usage: 45.3+ MB

id                0
week              0
center_id         0
meal_id           0
checkout_price    0
base_price        0
num_orders        0
category          0
cuisine           0
city_code         0
region_code       0
center_type       0
op_area           0
dtype: int64

In [11]:
data_top10k = data_top10k.copy()

In [12]:
# Discount
data_top10k["discount_percent"] = (
    (data_top10k["base_price"] - data_top10k["checkout_price"]) 
    / data_top10k["base_price"]
) * 100

# Revenue
data_top10k["revenue"] = data_top10k["checkout_price"] * data_top10k["num_orders"]

# Demand Level
data_top10k["demand_level"] = pd.cut(
    data_top10k["num_orders"],
    bins=[0, 5000, 15000, 30000],
    labels=["Low", "Medium", "High"]
)

In [13]:
data_top10k.head()

,id,week,center_id,meal_id,checkout_price,base_price,num_orders,category,cuisine,city_code,region_code,center_type,op_area,discount_percent,revenue,demand_level
14050,1452474,5,43,2290,159.08,311.43,24299,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,3865484.92,High
19700,1300512,7,43,2290,159.08,311.43,15336,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,2439650.88,High
16904,1087163,6,43,2290,156.20,310.43,14229,Rice Bowl,Indian,590,56,TYPE_A,5.1,49.682698,2222569.80,Medium
13923,1470267,5,10,2290,162.99,309.43,13580,Rice Bowl,Indian,590,56,TYPE_B,6.3,47.325728,2213404.20,Medium
413351,1346216,132,43,1971,204.70,324.04,13150,Sandwich,Italian,590,56,TYPE_A,5.1,36.828787,2691805.00,Medium

In [14]:
data_top10k = data_top10k.reset_index(drop=True)

In [15]:
data_top10k.head()

,id,week,center_id,meal_id,checkout_price,base_price,num_orders,category,cuisine,city_code,region_code,center_type,op_area,discount_percent,revenue,demand_level
0,1452474,5,43,2290,159.08,311.43,24299,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,3865484.92,High
1,1300512,7,43,2290,159.08,311.43,15336,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,2439650.88,High
2,1087163,6,43,2290,156.20,310.43,14229,Rice Bowl,Indian,590,56,TYPE_A,5.1,49.682698,2222569.80,Medium
3,1470267,5,10,2290,162.99,309.43,13580,Rice Bowl,Indian,590,56,TYPE_B,6.3,47.325728,2213404.20,Medium
4,1346216,132,43,1971,204.70,324.04,13150,Sandwich,Italian,590,56,TYPE_A,5.1,36.828787,2691805.00,Medium

In [16]:
data_top10k.to_csv("cleaned_data.csv", index=False)

In [18]:
avg_revenue = data_top10k['revenue'].mean()

data_top10k['revenue_category'] = data_top10k['revenue'].apply(
    lambda x: 'High' if x > avg_revenue else 'Low'
)

In [20]:
data_top10k['week_type'] = data_top10k['week'].apply(
    lambda x: 'Start' if x <= 17 else ('Mid' if x <= 35 else 'End')
)

In [21]:
avg_orders = data_top10k['num_orders'].mean()

data['meal_popularity'] = data_top10k['num_orders'].apply(
    lambda x: 'Popular' if x > avg_orders else 'Not Popular'
)

In [22]:
data_top10k.head()

,id,week,center_id,meal_id,checkout_price,base_price,num_orders,category,cuisine,city_code,region_code,center_type,op_area,discount_percent,revenue,demand_level,revenue_category,week_type
0,1452474,5,43,2290,159.08,311.43,24299,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,3865484.92,High,High,Start
1,1300512,7,43,2290,159.08,311.43,15336,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,2439650.88,High,High,Start
2,1087163,6,43,2290,156.20,310.43,14229,Rice Bowl,Indian,590,56,TYPE_A,5.1,49.682698,2222569.80,Medium,High,Start
3,1470267,5,10,2290,162.99,309.43,13580,Rice Bowl,Indian,590,56,TYPE_B,6.3,47.325728,2213404.20,Medium,High,Start
4,1346216,132,43,1971,204.70,324.04,13150,Sandwich,Italian,590,56,TYPE_A,5.1,36.828787,2691805.00,Medium,High,End

In [25]:
data_top10k['profit'] = (data_top10k['checkout_price'] - data_top10k['base_price']) * data_top10k['num_orders']

In [26]:
data_top10k.head()

,id,week,center_id,meal_id,checkout_price,base_price,num_orders,category,cuisine,city_code,region_code,center_type,op_area,discount_percent,revenue,demand_level,revenue_category,week_type,profit
0,1452474,5,43,2290,159.08,311.43,24299,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,3865484.92,High,High,Start,-3701952.65
1,1300512,7,43,2290,159.08,311.43,15336,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,2439650.88,High,High,Start,-2336439.60
2,1087163,6,43,2290,156.20,310.43,14229,Rice Bowl,Indian,590,56,TYPE_A,5.1,49.682698,2222569.80,Medium,High,Start,-2194538.67
3,1470267,5,10,2290,162.99,309.43,13580,Rice Bowl,Indian,590,56,TYPE_B,6.3,47.325728,2213404.20,Medium,High,Start,-1988655.20
4,1346216,132,43,1971,204.70,324.04,13150,Sandwich,Italian,590,56,TYPE_A,5.1,36.828787,2691805.00,Medium,High,End,-1569321.00

In [27]:
data_top10k.rename(columns={'id': 'order_id'}, inplace=True)

In [28]:
data_top10k.head()

,order_id,week,center_id,meal_id,checkout_price,base_price,num_orders,category,cuisine,city_code,region_code,center_type,op_area,discount_percent,revenue,demand_level,revenue_category,week_type,profit
0,1452474,5,43,2290,159.08,311.43,24299,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,3865484.92,High,High,Start,-3701952.65
1,1300512,7,43,2290,159.08,311.43,15336,Rice Bowl,Indian,590,56,TYPE_A,5.1,48.919500,2439650.88,High,High,Start,-2336439.60
2,1087163,6,43,2290,156.20,310.43,14229,Rice Bowl,Indian,590,56,TYPE_A,5.1,49.682698,2222569.80,Medium,High,Start,-2194538.67
3,1470267,5,10,2290,162.99,309.43,13580,Rice Bowl,Indian,590,56,TYPE_B,6.3,47.325728,2213404.20,Medium,High,Start,-1988655.20
4,1346216,132,43,1971,204.70,324.04,13150,Sandwich,Italian,590,56,TYPE_A,5.1,36.828787,2691805.00,Medium,High,End,-1569321.00

In [29]:
data_top10k.to_csv("food_analysis_cleaned.csv", index=False)